# This workflow will do a clean installation of node dependencies (using Yarn), cache/restore them, build the source code, and run tests using Jest across different versions of node.

name: Node.js CI with Yarn & Jest

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # Cache Yarn dependencies
      - run: yarn install --immutable  # Use Yarn to install dependencies
      - run: yarn build --if-present  # Build the project (if a build script exists)
      - run: yarn test --Verbose  # Run tests with Jest (and collect coverage if desired)
